# Generated by Django 4.0.2 on 2022-02-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa umiejętności')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Poziom')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa postaci')),
                ('birthdate', models.DateField(blank=True)),
                ('rank', models.IntegerField(choices=[(0, 'Kapitan'), (1, 'Sztabowy'), (2, 'Przystaniowiec')], default=2, verbose_name='Ranga')),
                ('function', models.IntegerField(choices=[(0, 'brak'), (1, 'Kwatermistrz')], default=0, verbose_name='Funkcja')),
                ('outpost', models.IntegerField(choices=[(0, 'O.R.P Kaszub'), (1, 'OldTown'), (2, 'TriCity'), (3, 'Północ'), (4, 'Nomad')], default=4, verbose_name='Placówka')),
                ('origin_outpost', models.CharField(blank=True, max_length=64, verbose_name='Miejsce pochodzenia')),
                ('job', models.CharField(blank=True, max_length=64, verbose_name='Zawód')),
                ('specialization', models.CharField(blank=True, max_length=64, verbose_name='Specjalizacje')),
                ('religion', models.CharField(blank=True, max_length=64, verbose_name='Wiara')),
                ('character_history', models.TextField(blank=True)),
                ('abilities', models.ManyToManyField(blank=True, null=True, to='kaszubnet_app.Ability', verbose_name='Umiejętności')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
        ),
    ]
