# Generated by Django 4.0.2 on 2022-02-08 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaszubnet_app', '0002_alter_ability_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2103)], verbose_name='Pory przybyszów')),
            ],
            options={
                'verbose_name': 'Edycja OT',
                'verbose_name_plural': 'Edycje OT',
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(to='kaszubnet_app.Ability', verbose_name='Umiejętności'),
        ),
        migrations.AddField(
            model_name='character',
            name='old_town_presence',
            field=models.ManyToManyField(to='kaszubnet_app.OTs', verbose_name='Pory Przybyszów'),
        ),
    ]
