# Generated by Django 4.0.2 on 2022-02-08 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kaszubnet_app', '0003_ots_alter_character_abilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64, verbose_name='Nazwa przedmiotu')),
                ('item_type', models.IntegerField(choices=[(0, 'Nienznany'), (1, 'Kapsel'), (2, 'Użytkowy'), (3, 'Materiał do produkcji'), (4, 'Medyczny'), (5, 'Elektronika')], verbose_name='Typ przedmiotu')),
                ('item_amount', models.IntegerField(blank=True, null=True, verbose_name='Ilosć')),
            ],
            options={
                'verbose_name': 'Magazyn',
                'verbose_name_plural': 'Magazyn',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Dodanie'), (1, 'Wybranie')], verbose_name='Akcja')),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kaszubnet_app.warehouse', verbose_name='Przedmiot')),
            ],
        ),
    ]
