# Generated by Django 4.0.2 on 2022-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaszubnet_app', '0006_warehouselog_amount_warehouselog_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='kaszubnet_app.Ability', verbose_name='Umiejętności'),
        ),
        migrations.AlterField(
            model_name='character',
            name='old_town_presence',
            field=models.ManyToManyField(blank=True, to='kaszubnet_app.OTs', verbose_name='Pory Przybyszów'),
        ),
    ]
